version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # Expose Qdrant on port 6333
    environment:
      QDRANT_LOG_LEVEL: "info"  # Optional: Set log level (debug, info, warn, error)
    volumes:
      - qdrant_data:/qdrant/storage  # Persist data

  
volumes:
  qdrant_data:
